export interface Note {
  id: string;
  title: string;
  description: string;
  userId: string; // Add this property to associate notes with users
}


export interface User {
    id: string;// A unique user ID generated by your system
    name: string; // User's full name
    email: string; // User's email address
    password: string // Encrypted or hashed password (do not store plaintext passwords)
  }
  

